openapi: 3.2.0
info:
  title: OpenAPI definition Secure Signature Controller API
  version: v0
servers:
- url: https://adminapi.incentivio.com/incentivio-admin-api
  description: Generated server url
tags:
- name: secure-signature-controller
paths:
  /chmlnsignature:
    get:
      tags:
      - secure-signature-controller
      operationId: generateSignature
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SignatureResponse'
components:
  schemas:
    SignatureResponse:
      type: object
      properties:
        uidHash:
          type: string
